### ISSUE TITLE
Does this work with new outlook 

### ISSUE THREAD

**Issue by abdcef** [acidix/OutlookURLHandler#1]
It seems that this may not work the new outlook for Mac. Even for the earlier versions, the message id is not constant for a given email.

**Comment by acidix** [comment]
I should probably mark it as deprecated. The new Outlook never had any AppleScript support, so the whole topic of script-based interaction basically is a dead end. Stopped using Outlook about a year ago, so there won't be any fixes from me either. Sorry about that!
